# -*- coding: utf-8 -*-
"""AnshikaKothari_DM_Final_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QgHo7p3t_0tW9V_nvJEgkWVNpkM5lORX

## Project Title
*Early Detection of personal finance stress using transaction patterns*

## Problem Definition
<div style="text-align: justify;">
The goal of this project is to identify and predict periods of financial stress using a single individual’s transaction history. We define stress as noticeable deviations from the person’s typical spending and cash-flow patterns. Using data mining techniques like frequent pattern mining, clustering, anomaly detection, and classification, we aim to model these behavioral changes.

We intentionally use a single-user dataset to capture within-person behavioral variations rather than population differences. Personal financial stress emerges when someone deviates from their own baseline, and these patterns are easier to detect when the data is not influenced by multiple users diverse financial profiles.
</div>

## Dataset Description
<div style="text-align: justify;">
The Mock Personal Finance Data dataset contains synthetic transaction records covering a period of almost four years, from January 1, 2020 to December 31, 2024. Each row represents a single financial transaction with the following fields:

Date – The exact day the transaction occurred.

Transaction Description – A short text explaining the transaction (e.g., “Grocery Store Purchase”, “Monthly Rent”).

Category – A labeled category such as Food & Drink, Rent, Utilities, Entertainment, as well as income types like Salary or Investment.

Amount – The monetary value of the transaction. Income entries generally have larger positive amounts, while expenses vary depending on the type.

Type – Indicates whether the transaction is an Income or an Expense.

Because the dataset spans multiple years and includes diverse spending and income categories, it is well-suited for analyzing personal financial behavior, tracking monthly spending, detecting unusual patterns, and studying financial stress indicators.
</div>

## Project Workflow
"""

# Hide DeprecationWarnings coming from Jupyter kernel
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

# Hide Jupyter client logs
import logging
logging.getLogger("jupyter_client").setLevel(logging.ERROR)
logging.getLogger("traitlets").setLevel(logging.ERROR)
logging.getLogger("asyncio").setLevel(logging.ERROR)
logging.getLogger("tornado").setLevel(logging.ERROR)

"""### Phase 1: Data Collection & Understanding"""

import pandas as pd
from google.colab import drive

# Upload dataset
drive.mount('/content/drive')
# Set path
DATA_PATH = "/content/drive/MyDrive/Data mining project/"

DATAFILE = "/content/drive/MyDrive/Personal_Finance_Dataset.csv"
df = pd.read_csv(DATAFILE)

# Parse Date with day-first (fix for DD/MM/YYYY)
if 'Date' in df.columns:
    df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, errors='coerce')

# Show first few records
print("\n--- Preview of Dataset (Head) ---")
display(df.head())

# Show columns
print("\n--- Column Names ---")
print(df.columns.tolist())

# Show shape
print("\n--- Dataset Shape (rows, columns) ---")
print(df.shape)

# Show data types
print("\n--- Data Types ---")
print(df.dtypes)

# Missing values check
print("\n--- Missing Values Per Column ---")
print(df.isnull().sum())

# Summary statistics for numeric columns
print("\n--- Summary Statistics (Numeric Columns) ---")
display(df.describe())

# Summary statistics for categorical columns
print("\n--- Summary Statistics (Categorical Columns) ---")
display(df.describe(include='object'))

# Phase 1 visuals: Raw distributions and timeline
import seaborn as sns
import matplotlib.pyplot as plt

# Raw amount distribution
if 'Amount' in df.columns:
    df['Amount'] = pd.to_numeric(df['Amount'], errors='coerce')
    plt.figure(figsize=(10,4)); sns.histplot(df['Amount'].dropna(), bins=50, kde=True); plt.title("Raw Transaction Amount Distribution"); plt.xlabel("Amount"); plt.tight_layout(); plt.savefig('p1_amount_dist.png', dpi=200); plt.show()

# Date coverage / timeline
if 'Date' in df.columns:
    df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, errors='coerce')
    timeline = df.sort_values('Date').reset_index(drop=True)
    plt.figure(figsize=(10,3)); plt.plot(timeline['Date'].values, range(len(timeline)), linewidth=1); plt.title("Data timeline (index vs date)"); plt.xlabel("Date"); plt.ylabel("Record index"); plt.tight_layout(); plt.savefig('p1_timeline.png', dpi=200); plt.show()

print("Phase 1 visuals saved: p1_amount_dist.png (if Amount), p1_timeline.png (if Date).")

"""### Phase 2: Data cleaning and Pre-processing"""

import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, RobustScaler
from sklearn.impute import SimpleImputer
from joblib import dump

# Remove duplicates
df_clean = df.drop_duplicates().reset_index(drop=True)

# Parse Date (day-first) and drop rows missing Date
df_clean['Date'] = pd.to_datetime(df_clean['Date'], dayfirst=True, errors='coerce')
df_clean = df_clean.dropna(subset=['Date']).reset_index(drop=True)

# Amount numeric + impute median if missing
df_clean['Amount'] = pd.to_numeric(df_clean['Amount'], errors='coerce')
df_clean['Amount'] = df_clean['Amount'].fillna(df_clean['Amount'].median())

# Time features
df_clean['Year'] = df_clean['Date'].dt.year
df_clean['Month'] = df_clean['Date'].dt.month
df_clean['Day'] = df_clean['Date'].dt.day
df_clean['Weekday'] = df_clean['Date'].dt.day_name()
df_clean['Week'] = df_clean['Date'].dt.isocalendar().week.astype(int)
df_clean['YYYYMM'] = df_clean['Date'].dt.to_period('M').astype(str)

# Preprocessing pipeline
numeric_features = ['Amount']
# Define optional categorical column safely
type_col = 'Type' if 'Type' in df_clean.columns else None
categorical_features = ['Category'] + ([type_col] if type_col else [])

numeric_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', RobustScaler())
])

categorical_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='constant', fill_value='Unknown')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ],
    remainder='drop'
)

pipeline = Pipeline([('preprocessor', preprocessor)])
pipeline.fit(df_clean[numeric_features + categorical_features])

# Save artifacts
dump(pipeline, 'preprocessing_pipeline.joblib')
df_clean.to_csv("cleaned_data.csv", index=False)

print("Phase 2 complete.")
print("Cleaned shape:", df_clean.shape)
print("Saved: cleaned_data.csv, preprocessing_pipeline.joblib")
display(df_clean.head())

# Phase 2 visuals: Before vs After cleaning checks
import os,seaborn as sns, matplotlib.pyplot as plt
sns.set(style="whitegrid")
plt.rcParams['figure.figsize'] = (10,5)

# Amount distribution : Before vs After
if 'Amount' in df.columns and 'Amount' in df_clean.columns:
    plt.figure(figsize=(10,5))
    sns.kdeplot(df['Amount'].dropna(), label='Before', bw_adjust=0.5)
    sns.kdeplot(df_clean['Amount'].dropna(), label='After', bw_adjust=0.5)
    plt.title("Amount Distribution: Before vs After Cleaning")
    plt.xlabel("Amount")
    plt.legend()
    plt.tight_layout(); plt.savefig('p2_amount_before_after.png', dpi=200); plt.show()

# Date range comparison
def date_range_text(dframe):
    if 'Date' in dframe.columns:
        dmin = pd.to_datetime(dframe['Date'], errors='coerce').min()
        dmax = pd.to_datetime(dframe['Date'], errors='coerce').max()
        return f"{dmin.date() if pd.notna(dmin) else 'NA'} → {dmax.date() if pd.notna(dmax) else 'NA'}"
    return "No Date"
plt.figure(figsize=(8,1))
plt.axis('off')
txt = f"Raw date range: {date_range_text(df)}\nCleaned date range: {date_range_text(df_clean)}"
plt.text(0,0.5, txt, fontsize=12)
plt.savefig('p2_date_ranges.png', dpi=200, bbox_inches='tight'); plt.show()

print("Phase 2 visuals saved: p2_amount_before_after.png (if Amount),p2_date_ranges.png.")

"""### Phase 3: Exploratory Data Analysis (EDA)

#### 1) Distribution of Transaction Amounts & Frequency

A. Histogram + KDE (Amount Distribution)
"""

plt.figure(figsize=(10,5))
sns.histplot(df_clean["Amount"], bins=40, kde=True)
plt.title("Distribution of Transaction Amounts")
plt.xlabel("Amount")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

"""B. Frequency of Transactions per Day"""

import matplotlib.dates as mdates

# Ensure Date is datetime and sorted
df_clean['Date'] = pd.to_datetime(df_clean['Date'], errors='coerce')
df_clean = df_clean.dropna(subset=['Date']).sort_values('Date').reset_index(drop=True)

# Daily frequency
daily_freq = df_clean.groupby('Date').size()

# Debug: show range
print("Date range:", daily_freq.index.min().date(), "to", daily_freq.index.max().date(), " — rows:", len(daily_freq))

# Plot
plt.figure(figsize=(12,4))
sns.lineplot(x=daily_freq.index, y=daily_freq.values)

plt.title("Daily Transaction Frequency")
plt.xlabel("Transaction Timeline")
plt.ylabel("Number of Transactions")

ax = plt.gca()
locator = mdates.AutoDateLocator()
formatter = mdates.AutoDateFormatter(locator)
ax.xaxis.set_major_locator(locator)
ax.xaxis.set_major_formatter(formatter)

plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""#### 2) Spending Trends Per Category / Over Time

A. Monthly Spending Trend
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

# Prepare monthly series and ensure a datetime at month-start
monthly = df_clean.groupby('YYYYMM')['Amount'].sum().reset_index()
monthly['month_dt'] = pd.to_datetime(monthly['YYYYMM'] + '-01', format='%Y-%m-%d', errors='coerce')
monthly = monthly.sort_values('month_dt').set_index('month_dt')['Amount']

# Build full month index from min to max month and fill missing with 0
full_idx = pd.date_range(start=monthly.index.min(), end=monthly.index.max(), freq='MS')
monthly = monthly.reindex(full_idx, fill_value=0)

# Adjust figure width based on number of months
n = len(monthly)
fig_w = max(12, n * 0.25)  # tweak multiplier if you want denser/sparser layout
plt.figure(figsize=(fig_w, 4.5))
plt.plot(monthly.index, monthly.values, marker='o', linewidth=1)
plt.title("Monthly Spending Trend")
plt.xlabel("Month")
plt.ylabel("Total Amount")

# Format label
labels = [d.strftime('%b %Y') for d in monthly.index]
plt.xticks(monthly.index, labels, rotation=90, fontsize=8)

plt.tight_layout()
plt.savefig('viz_monthly_all_months.png', dpi=300, bbox_inches='tight')
plt.show()

"""B. Spending per Category"""

cat_spend = df_clean.groupby("Category")["Amount"].sum().sort_values(ascending=False)

plt.figure(figsize=(10,5))
sns.barplot(x=cat_spend.values, y=cat_spend.index)
plt.title("Total Spending by Category")
plt.xlabel("Amount")
plt.ylabel("Category")
plt.tight_layout()
plt.show()

"""#### 3) Outliers & Seasonal Cycles

A. IQR-Based Outlier Detection
"""

Q1 = df_clean["Amount"].quantile(0.25)
Q3 = df_clean["Amount"].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df_clean["Outlier"] = (df_clean["Amount"] < lower) | (df_clean["Amount"] > upper)

plt.figure(figsize=(12,5))
sns.scatterplot(x="Date", y="Amount", data=df_clean, hue="Outlier", palette=["blue","red"])
plt.title("Outlier Detection (IQR Method)")
plt.xlabel("Date")
plt.ylabel("Amount")
plt.tight_layout()
plt.show()

"""B. Seasonal Pattern Heatmap (Weekday vs Month)"""

weekday_order = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
pivot = df_clean.pivot_table(
    index="Weekday",
    columns="Month",
    values="Amount",
    aggfunc="sum",
    fill_value=0
)
pivot = pivot.reindex(weekday_order)

plt.figure(figsize=(12,6))
sns.heatmap(pivot, cmap="RdYlGn_r", linewidths=0.5)
plt.title("Seasonal Spending Heatmap (Weekday vs Month)")
plt.tight_layout()
plt.show()

"""#### 4) Correlation Analysis Between Features"""

num_cols = ["Amount", "Year", "Month", "Day"]
corr = df_clean[num_cols].corr()

plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap="coolwarm", vmin=-1, vmax=1)
plt.title("Feature Correlation Heatmap")
plt.tight_layout()
plt.show()

"""#### 5) Boxplots by Category"""

plt.figure(figsize=(12,6))
sns.boxplot(x="Category", y="Amount", data=df_clean)
plt.xticks(rotation=30)
plt.title("Spending Distribution per Category (Boxplot)")
plt.tight_layout()
plt.show()

"""### Phase 4: Feature Engineering"""

from scipy.stats import skew, kurtosis

# If no user column, create one
df_clean['UserID'] = 'User_1'

# Monthly spend
monthly_spend = df_clean.groupby(['UserID', 'YYYYMM'])['Amount'].sum().reset_index()

# Basic features
user_features = df_clean.groupby('UserID').agg(
    total_spend = ('Amount', 'sum'),
    avg_monthly_spend = ('Amount', 'mean'),
    max_spend = ('Amount', 'max'),
    min_spend = ('Amount', 'min'),
    spend_volatility = ('Amount', 'std')
).reset_index()

# Frequency of transactions per week
weekly_freq = df_clean.groupby(['UserID', 'Week']).size().groupby('UserID').mean()
user_features['avg_weekly_txn'] = user_features['UserID'].map(weekly_freq)

# Spending growth rate (last month vs first month)
first_month = monthly_spend.groupby('UserID').first().reset_index()
last_month  = monthly_spend.groupby('UserID').last().reset_index()

user_features['growth_rate'] = (last_month['Amount'].values - first_month['Amount'].values) / \
                                first_month['Amount'].replace(0, np.nan).values

# Category ratio: essential vs non-essential
essential = ['Utilities','Rent','Food & Drink','Health & Fitness']

df_clean['IsEssential'] = df_clean['Category'].isin(essential).astype(int)

cat_stats = df_clean.groupby('UserID')['IsEssential'].mean()
user_features['pct_essential'] = user_features['UserID'].map(cat_stats)

# Category diversity index (Shannon entropy)
def shannon_entropy(x):
    p = x.value_counts(normalize=True)
    return -(p * np.log(p)).sum()

entropy = df_clean.groupby('UserID')['Category'].apply(shannon_entropy)
user_features['category_diversity'] = user_features['UserID'].map(entropy)

# Statistical features
stats_df = df_clean.groupby('UserID')['Amount'].agg(
    amount_skew = lambda x: skew(x),
    amount_kurtosis = lambda x: kurtosis(x),
    median_mean_ratio = lambda x: np.median(x) / (np.mean(x) if np.mean(x)!=0 else np.nan)
)

user_features = user_features.merge(stats_df, on='UserID', how='left')

# Final output
print("User-level feature dataset:")
display(user_features)

user_features.to_csv("user_features.csv", index=False)
print("Saved: user_features.csv")

"""### Phase 5: Frequent Pattern mining ( Data Mining Technique # 1 )"""

!pip install -q mlxtend

"""Step 1 — Prepare baskets *(Each basket = categories used in a given month)*"""

import pandas as pd
from mlxtend.frequent_patterns import apriori, fpgrowth, association_rules

# Ensure YYYYMM exists
if 'YYYYMM' not in df_clean.columns:
    df_clean['YYYYMM'] = df_clean['Date'].dt.to_period('M').astype(str)

# Create monthly basket: for each month, list categories
monthly_categories = df_clean.groupby('YYYYMM')['Category'].apply(list).reset_index()
monthly_categories.head()

"""Step 2 — Convert baskets into one-hot encoded format (Transaction Matrix)"""

# Ensure YYYYMM exists
df_clean['YYYYMM'] = pd.to_datetime(df_clean['Date']).dt.to_period('M').astype(str)

# One-hot categories per transaction then aggregate by month (presence)
dummies = pd.get_dummies(df_clean['Category'])
basket_matrix = pd.concat([df_clean[['YYYYMM']], dummies], axis=1).groupby('YYYYMM').max()

# Convert boolean to int
basket_matrix = basket_matrix.astype(int)

display(basket_matrix.head())
basket_matrix.to_csv("basket_matrix_monthly.csv")

"""Step 3 — Run Frequent Pattern Mining

1. FP Growth
"""

freq_items = fpgrowth(basket_matrix, min_support=0.2, use_colnames=True)
freq_items.sort_values('support', ascending=False, inplace=True)
freq_items.head()

rules = association_rules(freq_items, metric="lift", min_threshold=1.0)
rules = rules.sort_values(['lift', 'confidence'], ascending=False)
display(rules.head(5))

"""2. Apriori"""

freq_items1 = apriori(basket_matrix, min_support=0.2, use_colnames=True)
freq_items1.sort_values('support', ascending=False, inplace=True)
freq_items1.head()

rules = association_rules(freq_items1, metric="lift", min_threshold=1.0)
rules = rules.sort_values(['lift', 'confidence'], ascending=False)
display(rules.head(5))

"""*Comparative study*"""

import time, pandas as pd
from mlxtend.frequent_patterns import apriori, fpgrowth

def time_method(method, matrix, min_support=0.2, max_len=None):
    t0 = time.time()
    if method=='fp':
        res = fpgrowth(matrix, min_support=min_support, use_colnames=True, max_len=max_len)
    else:
        res = apriori(matrix, min_support=min_support, use_colnames=True, max_len=max_len)
    return time.time()-t0, res

# Prune rare cols
col_freq = basket_matrix.sum(axis=0) / len(basket_matrix)
keep = col_freq[col_freq>=0.02].index
bm = basket_matrix[keep]

for s in (0.1, 0.15, 0.2):
    t_fp, r_fp = time_method('fp', bm, min_support=s, max_len=3)
    t_ap, r_ap = time_method('ap', bm, min_support=s, max_len=3)
    print(s, "FP:", round(t_fp,3), "n_itemsets", len(r_fp), " | Apriori:", round(t_ap,3), "n_itemsets", len(r_ap))

"""### Phase 6: Clustering ( Data Mining Technique # 2 )

Step 1 - Create window_features
"""

# Create window_features.csv (monthly features)
import pandas as pd, numpy as np
from scipy.stats import skew, kurtosis

df_clean = pd.read_csv("cleaned_data.csv")
df_clean['Date'] = pd.to_datetime(df_clean['Date'], dayfirst=True, errors='coerce')
df_clean['YYYYMM'] = df_clean['Date'].dt.to_period('M').astype(str)

def shannon_entropy(x):
    p = x.value_counts(normalize=True)
    return -np.sum(p * np.log(p+1e-12))

essential = ['Utilities','Rent','Food & Drink','Health & Fitness']

df_clean['IsEssential'] = df_clean['Category'].isin(essential).astype(int)

window = df_clean.groupby("YYYYMM").agg(
    Amount_sum=("Amount","sum"),
    Amount_mean=("Amount","mean"),
    Amount_median=("Amount","median"),
    Amount_max=("Amount","max"),
    Amount_std=("Amount","std"),
    txn_count=("Amount","count"),
    category_entropy=("Category", shannon_entropy),
    pct_essential=("IsEssential","mean")
)

window["spend_volatility"] = window["Amount_std"].fillna(0)
window["median_mean_ratio"] = window["Amount_median"] / (window["Amount_mean"].replace(0,np.nan))

window["amount_skew"] = df_clean.groupby("YYYYMM")["Amount"].apply(lambda x: skew(x.dropna()))
window["amount_kurtosis"] = df_clean.groupby("YYYYMM")["Amount"].apply(lambda x: kurtosis(x.dropna()))

window = window.fillna(0)
window_features = window.reset_index()
window_features.to_csv("window_features.csv", index=False)

window_features.head()

"""Step 2 - Prepare for clustering"""

# Preparation for clustering
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

window_features = pd.read_csv("window_features.csv")

feat_cols = [c for c in window_features.columns if c not in ("YYYYMM","pca1","pca2")]
X = window_features[feat_cols].values

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

window_features["pca1"] = X_pca[:,0]
window_features["pca2"] = X_pca[:,1]

import pandas as pd

pca_components = pd.DataFrame(
    pca.components_,
    columns=feat_cols,
    index=['PCA1', 'PCA2']
)

print("PCA Loadings (what each PCA dimension means):")
display(pca_components.T)

"""Step 3 - Different clustering methods

1) KMeans Clustering
"""

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, davies_bouldin_score
import seaborn as sns
import matplotlib.pyplot as plt

k = 3
km = KMeans(n_clusters=k, random_state=42)
labels = km.fit_predict(X_scaled)

window_features["cluster_kmeans"] = labels

window_features[['YYYYMM', 'cluster_kmeans']].sort_values('cluster_kmeans')
for c in sorted(window_features['cluster_kmeans'].unique()):
    print(f"\nCluster {c}:")
    display(window_features[window_features['cluster_kmeans'] == c][['YYYYMM']])

print("Silhouette:", silhouette_score(X_scaled, labels))
print("DB Index:", davies_bouldin_score(X_scaled, labels))

sns.scatterplot(x="pca1", y="pca2", hue="cluster_kmeans",
                data=window_features, palette="tab10", s=80)
plt.title("K-Means Clusters (PCA)")
plt.xlabel("Spending Intensity (PCA1)")
plt.ylabel("Category Diversity (PCA2)")
plt.show()

window_features.to_csv("clustered_window_features_kmeans.csv", index=False)

"""2) DBSCAN"""

import numpy as np, pandas as pd
from sklearn.cluster import DBSCAN
from sklearn.metrics import silhouette_score, davies_bouldin_score
import matplotlib.pyplot as plt
import seaborn as sns

# Parameters
eps = 2.0
min_samples = 5

# Run DBSCAN
dbscan_model = DBSCAN(eps=eps, min_samples=min_samples)
labels_db = dbscan_model.fit_predict(X_scaled)

window_features = window_features.copy()
window_features['cluster_dbscan'] = labels_db

# Compute cluster counts and valid clusters (exclude noise = -1)
counts = window_features['cluster_dbscan'].value_counts().sort_index()
print("Cluster counts (including noise=-1):")
print(counts.to_string())

valid_labels = [lab for lab in np.unique(labels_db) if lab != -1]
n_valid_clusters = len(valid_labels)
print("Number of DBSCAN clusters (excluding noise):", n_valid_clusters)

# Silhouette / DB index: compute on non-noise points only (requires >=2 clusters)
if n_valid_clusters < 2:
    print("DBSCAN did not form enough clusters (>=2) for silhouette/DB index.")
    sil = np.nan
    db_index = np.nan
else:

    # Subset X_scaled and labels to exclude noise
    mask = window_features['cluster_dbscan'] != -1
    X_sub = X_scaled[mask]
    labels_sub = window_features.loc[mask, 'cluster_dbscan'].values
    sil = silhouette_score(X_sub, labels_sub)
    db_index = davies_bouldin_score(X_sub, labels_sub)
    print("Silhouette Score (non-noise subset):", round(sil,4))
    print("Davies–Bouldin Index (non-noise subset):", round(db_index,4))

# For plotting, convert -1 => 'noise' for readability
plot_df = window_features.copy()
plot_df['cluster_dbscan_plot'] = plot_df['cluster_dbscan'].apply(lambda x: 'noise' if x == -1 else f"c{x}")

plt.figure(figsize=(8,6))
sns.scatterplot(data=plot_df, x='pca1', y='pca2', hue='cluster_dbscan_plot', palette='tab10', s=80, linewidth=0)
plt.title("DBSCAN Clusters (PCA)")
plt.xlabel("Spending Intensity 1 (PCA1)")
plt.ylabel("Spending Intensity 2 (PCA2)")
plt.legend(title='Cluster', bbox_to_anchor=(1.02,1))
plt.tight_layout()
plt.show()

# Save outputs
window_features.to_csv("clustered_window_features_dbscan.csv", index=False)
print("Saved: clustered_window_features_dbscan.csv")

"""*Comparative study*"""

import os, pandas as pd, numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, DBSCAN
from sklearn.metrics import silhouette_score, davies_bouldin_score

if 'window_features' not in globals():
    if os.path.exists("window_features.csv"):
        window_features = pd.read_csv("window_features.csv")
    else:
        raise FileNotFoundError("window_features.csv not found. Run Phase 4/6 prep first.")

feat_cols = [c for c in window_features.columns if c not in ("YYYYMM","pca1","pca2")]
X = window_features[feat_cols].replace([np.inf,-np.inf],0).fillna(0).values
X_scaled = StandardScaler().fit_transform(X)

# Run KMeans
k = 3
km = KMeans(n_clusters=k, random_state=42, n_init=10).fit(X_scaled)
labels_k = km.labels_

# Run DBSCAN (tune eps/min as needed)
db = DBSCAN(eps=2.0, min_samples=5).fit(X_scaled)
labels_db = db.labels_

def stats(Xs, labels):
    unique = set(labels)
    n_clusters = len([l for l in unique if l != -1])
    noise_ratio = (labels == -1).sum() / len(labels)
    sil = silhouette_score(Xs, labels) if len(set(labels))>1 and n_clusters>0 else float("nan")
    dbi = davies_bouldin_score(Xs, labels) if len(set(labels))>1 and n_clusters>0 else float("nan")
    return n_clusters, round(noise_ratio,3), round(sil,4) if pd.notna(sil) else sil, round(dbi,4) if pd.notna(dbi) else dbi

k_n, k_noise, k_sil, k_dbi = stats(X_scaled, labels_k)
d_n, d_noise, d_sil, d_dbi = stats(X_scaled, labels_db)

cmp = pd.DataFrame([
    {'method':'kmeans','n_clusters':k_n,'noise_ratio':k_noise,'silhouette':k_sil,'davies_bouldin':k_dbi},
    {'method':'dbscan','n_clusters':d_n,'noise_ratio':d_noise,'silhouette':d_sil,'davies_bouldin':d_dbi}
])
print(cmp)
cmp.to_csv("compare_kmeans_dbscan_summary.csv", index=False)

window_features['cluster_kmeans'] = labels_k
window_features['cluster_dbscan'] = labels_db
window_features.to_csv("window_features_with_clusters.csv", index=False)
print("Saved window_features_with_clusters.csv and compare_kmeans_dbscan_summary.csv")
print("\nKMeans cluster sizes:")
print(window_features['cluster_kmeans'].value_counts().to_string())
print("\nDBSCAN label counts:")
print(window_features['cluster_dbscan'].value_counts().to_string())

"""### Phase 7: Hybrid Anomaly Detection ( Data Mining Technique # 3 - Novel Algorithm Modification)

1) Cluster-wise Isolation Forest
"""

# Cluster-wise Isolation Forest
import os, pandas as pd, numpy as np
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import MinMaxScaler

# Parameters
ISOF_CONTAMINATION = 0.02
TOP_K_PER_CLUSTER = 10
PCT_THRESHOLD = 0.98

# Load Data
df = pd.read_csv("cleaned_data.csv")
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
wf = pd.read_csv("window_features_with_clusters.csv")
wf_map = wf[['YYYYMM','cluster_kmeans']].drop_duplicates().rename(columns={'cluster_kmeans':'cluster'})
df['YYYYMM'] = df['Date'].dt.to_period('M').astype(str)
df = df.merge(wf_map, on='YYYYMM', how='left')
df['cluster'] = df['cluster'].fillna(-1).astype(int)
df = df.sort_values('Date').reset_index(drop=True)

# Prepare storage
res = df[['Date','YYYYMM','Amount','Category','cluster']].copy()
res['isof_raw'] = 0.0

# Cluster-wise fit
clusters = sorted(res['cluster'].unique())
for cl in clusters:
    idx = res[res['cluster']==cl].index
    vals = res.loc[idx,'Amount'].values.reshape(-1,1)
    if len(vals) >= 10:
        iso = IsolationForest(contamination=ISOF_CONTAMINATION, random_state=42)
        iso.fit(vals)
        raw = -iso.score_samples(vals)  # higher => more anomalous
    else:
        # Fallback to global model
        iso = IsolationForest(contamination=ISOF_CONTAMINATION, random_state=42)
        iso.fit(res['Amount'].values.reshape(-1,1))
        raw = -iso.score_samples(vals)
    res.loc[idx,'isof_raw'] = raw

# Normalize per-cluster
res['isof_score'] = 0.0
for cl in clusters:
    idx = res[res['cluster']==cl].index
    if len(idx)==0:
        continue
    arr = res.loc[idx,'isof_raw'].values.reshape(-1,1)
    if arr.shape[0] <= 1 or np.allclose(arr, arr[0]):
        norm = (arr - arr.min()) / (arr.max()-arr.min()+1e-9)
    else:
        norm = MinMaxScaler().fit_transform(arr)
    res.loc[idx,'isof_score'] = norm.ravel()

# Flags
res['isof_topk'] = False
for cl in clusters:
    idx = res[res['cluster']==cl].index
    if len(idx)==0: continue
    k = int(min(TOP_K_PER_CLUSTER, max(1, len(idx)//10)))
    top_idx = res.loc[idx].sort_values('isof_score', ascending=False).head(k).index
    res.loc[top_idx,'isof_topk'] = True

res['isof_pct'] = res['isof_score'] >= res['isof_score'].quantile(PCT_THRESHOLD)
res['isof_abs'] = res['isof_score'] >= 0.6

res.to_csv("isof_results.csv", index=False)
print("Saved: isof_results.csv")
print("Overall flagged (pct):", round(res['isof_pct'].mean(),4))

isof = pd.read_csv("isof_results.csv", parse_dates=['Date'])

def summary_stats(df, score_col, flag_cols):
    s = {}
    s['n_rows'] = len(df)
    s['mean_score'] = float(df[score_col].mean())
    s['median_score'] = float(df[score_col].median())
    s['std_score'] = float(df[score_col].std())
    for f in flag_cols:
        s[f'_count_{f}'] = int(df[f].sum())
        s[f'_pct_{f}'] = float(df[f].mean())
    return s

print("=== Isolation Forest: Overall Stats ===")
overall = summary_stats(isof, 'isof_score', ['isof_topk','isof_pct','isof_abs'])
for k,v in overall.items():
    print(f"{k}: {v}")

print("\n=== Isolation Forest: Per-cluster Summary ===")
per_cluster = isof.groupby('cluster').apply(lambda d: pd.Series(summary_stats(d, 'isof_score', ['isof_topk','isof_pct','isof_abs']))).reset_index()
display(per_cluster)

print("\n=== Isolation Forest: Top 15 by score ===")
display(isof.sort_values('isof_score', ascending=False).head(15)[['Date','Amount','Category','cluster','isof_score','isof_pct','isof_topk','isof_abs']])

"""2. Cluster-wise One-Class SVM"""

from sklearn.svm import OneClassSVM
from sklearn.preprocessing import MinMaxScaler

# Parameters
OCSVm_NU = 0.02
TOP_K_PER_CLUSTER = 10
PCT_THRESHOLD = 0.98

# Load Data
df = pd.read_csv("cleaned_data.csv")
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
wf = pd.read_csv("window_features_with_clusters.csv")
wf_map = wf[['YYYYMM','cluster_kmeans']].drop_duplicates().rename(columns={'cluster_kmeans':'cluster'})
df['YYYYMM'] = df['Date'].dt.to_period('M').astype(str)
df = df.merge(wf_map, on='YYYYMM', how='left')
df['cluster'] = df['cluster'].fillna(-1).astype(int)
df = df.sort_values('Date').reset_index(drop=True)

res2 = df[['Date','YYYYMM','Amount','Category','cluster']].copy()
res2['ocsvm_raw'] = 0.0

clusters = sorted(res2['cluster'].unique())
for cl in clusters:
    idx = res2[res2['cluster']==cl].index
    vals = res2.loc[idx,'Amount'].values.reshape(-1,1)
    if len(vals) >= 10:
        oc = OneClassSVM(nu=OCSVm_NU, kernel='rbf', gamma='scale')
        oc.fit(vals)
        # Decision_function: positive for inliers; invert so higher => anomalous
        raw = -oc.decision_function(vals).ravel()
    else:
        # Fallback global
        ocg = OneClassSVM(nu=OCSVm_NU, kernel='rbf', gamma='scale')
        ocg.fit(res2['Amount'].values.reshape(-1,1))
        raw = -ocg.decision_function(vals).ravel()
    res2.loc[idx,'ocsvm_raw'] = raw

# Normalize per-cluster
res2['ocsvm_score'] = 0.0
for cl in clusters:
    idx = res2[res2['cluster']==cl].index
    if len(idx)==0: continue
    arr = res2.loc[idx,'ocsvm_raw'].values.reshape(-1,1)
    if arr.shape[0] <= 1 or np.allclose(arr, arr[0]):
        norm = (arr - arr.min()) / (arr.max()-arr.min()+1e-9)
    else:
        norm = MinMaxScaler().fit_transform(arr)
    res2.loc[idx,'ocsvm_score'] = norm.ravel()

# Flags
res2['ocsvm_topk'] = False
for cl in clusters:
    idx = res2[res2['cluster']==cl].index
    if len(idx)==0: continue
    k = int(min(TOP_K_PER_CLUSTER, max(1, len(idx)//10)))
    top_idx = res2.loc[idx].sort_values('ocsvm_score', ascending=False).head(k).index
    res2.loc[top_idx,'ocsvm_topk'] = True

res2['ocsvm_pct'] = res2['ocsvm_score'] >= res2['ocsvm_score'].quantile(PCT_THRESHOLD)
res2['ocsvm_abs'] = res2['ocsvm_score'] >= 0.6

res2.to_csv("ocsvm_results.csv", index=False)
print("Saved: ocsvm_results.csv")
print("Overall flagged (pct):", round(res2['ocsvm_pct'].mean(),4))

ocsvm = pd.read_csv("ocsvm_results.csv", parse_dates=['Date'])

print("=== One-Class SVM: Overall Stats ===")
overall_oc = summary_stats(ocsvm, 'ocsvm_score', ['ocsvm_topk','ocsvm_pct','ocsvm_abs'])
for k,v in overall_oc.items():
    print(f"{k}: {v}")

print("\n=== One-Class SVM: Per-cluster Summary ===")
per_cluster_oc = ocsvm.groupby('cluster').apply(lambda d: pd.Series(summary_stats(d, 'ocsvm_score', ['ocsvm_topk','ocsvm_pct','ocsvm_abs']))).reset_index()
display(per_cluster_oc)

print("\n=== One-Class SVM: Top 15 by score ===")
display(ocsvm.sort_values('ocsvm_score', ascending=False).head(15)[['Date','Amount','Category','cluster','ocsvm_score','ocsvm_pct','ocsvm_topk','ocsvm_abs']])

"""*Comparative study*"""

isof = pd.read_csv("isof_results.csv", parse_dates=["Date"])
ocsvm = pd.read_csv("ocsvm_results.csv", parse_dates=["Date"])

# Align rows by index
cmp = pd.DataFrame({
    "Date": isof["Date"],
    "Amount": isof["Amount"],
    "YYYYMM": isof["YYYYMM"],
    "Cluster": isof["cluster"],
    "ISOF_Score": isof["isof_score"],
    "ISOF_Flag": isof["isof_pct"],
    "OCSVM_Score": ocsvm["ocsvm_score"],
    "OCSVM_Flag": ocsvm["ocsvm_pct"]
})

# Global comparison
n = len(cmp)

isof_total = cmp["ISOF_Flag"].sum()
ocsvm_total = cmp["OCSVM_Flag"].sum()
both_total = ((cmp["ISOF_Flag"]) & (cmp["OCSVM_Flag"])).sum()
either_total = ((cmp["ISOF_Flag"]) | (cmp["OCSVM_Flag"])).sum()
jaccard = both_total / (either_total + 1e-9)

print("===== GLOBAL ANOMALY DETECTOR COMPARISON =====")
print(f"Total transactions: {n}")
print(f"Isolation Forest flagged: {isof_total}  ({isof_total/n:.4f})")
print(f"One-Class SVM flagged:    {ocsvm_total}  ({ocsvm_total/n:.4f})")
print(f"Both flagged:             {both_total}")
print(f"Jaccard Similarity:       {jaccard:.4f}")
print("\n")

# Per cluster comparison
cluster_stats = (
    cmp.groupby("Cluster")
    .apply(lambda df: pd.Series({
        "n_txn": len(df),
        "ISOF_Flagged": df["ISOF_Flag"].sum(),
        "OCSVM_Flagged": df["OCSVM_Flag"].sum(),
        "Both_Flagged": ((df["ISOF_Flag"]) & (df["OCSVM_Flag"])).sum(),
        "ISOF_Ratio": df["ISOF_Flag"].mean(),
        "OCSVM_Ratio": df["OCSVM_Flag"].mean(),
        "Jaccard": ((df["ISOF_Flag"] & df["OCSVM_Flag"]).sum() /
                    ((df["ISOF_Flag"] | df["OCSVM_Flag"]).sum() + 1e-9))
    }))
    .reset_index()
)

print("===== PER-CLUSTER COMPARISON =====")
display(cluster_stats)
print("\n")

# Show Top 10 anamolies from each detector
print("===== TOP 10 ISOF Anomalies =====")
display(cmp.sort_values("ISOF_Score", ascending=False).head(10))

print("\n===== TOP 10 OCSVM Anomalies =====")
display(cmp.sort_values("OCSVM_Score", ascending=False).head(10))

# Disagreements
print("\n===== ISOF flagged but OCSVM did NOT =====")
display(cmp[(cmp["ISOF_Flag"] == True) & (cmp["OCSVM_Flag"] == False)].sort_values("ISOF_Score", ascending=False).head(10))

print("\n===== OCSVM flagged but ISOF did NOT =====")
display(cmp[(cmp["OCSVM_Flag"] == True) & (cmp["ISOF_Flag"] == False)].sort_values("OCSVM_Score", ascending=False).head(10))

# Robust Anomaly timeline + Top anomalies export (handles missing 'cluster')
import os, pandas as pd, numpy as np, matplotlib.pyplot as plt
from datetime import datetime

# Parameters
ANOMALY_PCT = 0.98   # percentile threshold when using hybrid_score
TOPK = 20            # number of top anomalies to export

HYB = "hybrid_anomaly_results.csv"
ISO = "isof_results.csv"
OCS = "ocsvm_results.csv"
WF  = "window_features_with_clusters.csv"
OUT_PNG = "anomaly_timeline.png"
OUT_TOP = "top_anomalies.csv"

# Load or build hybrid anomalies dataframe
if os.path.exists(HYB):
    hy = pd.read_csv(HYB, parse_dates=['Date'], infer_datetime_format=True)
    print("Loaded", HYB)
elif os.path.exists(ISO) and os.path.exists(OCS):
    a = pd.read_csv(ISO, parse_dates=['Date'], infer_datetime_format=True)
    b = pd.read_csv(OCS, parse_dates=['Date'], infer_datetime_format=True)

    # Align by Date and Amount where possible
    hy = a[['Date','Amount','Category']].copy()

    # Try to bring scores from both; if missing use zeros
    hy['isof_score'] = a.get('isof_score', a.get('score', 0))
    hy['ocsvm_score'] = b.get('ocsvm_score', b.get('score', 0))
    hy['hybrid_score'] = (hy['isof_score'].fillna(0) + hy['ocsvm_score'].fillna(0)) / 2
    hy['hybrid_flag'] = hy['hybrid_score'] >= hy['hybrid_score'].quantile(ANOMALY_PCT)
    hy.to_csv(HYB, index=False)
    print("Built hybrid from ISOF+OCSVM and saved to", HYB)
else:
    raise FileNotFoundError("Provide hybrid_anomaly_results.csv OR both isof_results.csv and ocsvm_results.csv.")

# Ensure Date and YYYYMM exist
hy['Date'] = pd.to_datetime(hy['Date'], errors='coerce')
if hy['Date'].isna().any():
    print("Warning: some Date values could not be parsed; check hy['Date'].isna().sum() for count.")
hy['YYYYMM'] = hy['Date'].dt.to_period('M').astype(str)

# Try to merge cluster info from window_features_with_clusters.csv
if os.path.exists(WF):
    wf = pd.read_csv(WF)

    # Ensure wf has YYYYMM; create if it has Date
    if 'YYYYMM' not in wf.columns and 'Date' in wf.columns:
        wf['Date'] = pd.to_datetime(wf['Date'], errors='coerce')
        wf['YYYYMM'] = wf['Date'].dt.to_period('M').astype(str)
    if 'YYYYMM' in wf.columns and 'cluster' in wf.columns:

        # Merge cluster into hy by YYYYMM (many-to-one mapping)
        hy = hy.merge(wf[['YYYYMM','cluster']].drop_duplicates(), on='YYYYMM', how='left')
        print("Merged cluster from", WF)
    else:
        print("Warning: WF exists but lacks 'YYYYMM' or 'cluster' columns; skipping cluster merge.")
else:
    print("No window_features_with_clusters.csv found — proceeding without cluster mapping.")

# Sort and identify anomalies (robust logic)
hy = hy.sort_values('Date').reset_index(drop=True)

# Determine anomalies using priority:
# 1) Hybrid_flag column if present
# 2) Anomaly_abs or anomaly_flag if present
# 3) Hybrid_score quantile threshold
# 4) Fallback: top TOPK by Amount
if 'hybrid_flag' in hy.columns:
    anoms = hy[hy['hybrid_flag']==True].copy()
    method = "hybrid_flag"
elif 'anomaly_abs' in hy.columns:
    anoms = hy[hy['anomaly_abs']==True].copy()
    method = "anomaly_abs"
elif 'hybrid_score' in hy.columns:
    thr = hy['hybrid_score'].quantile(ANOMALY_PCT)
    anoms = hy[hy['hybrid_score'] >= thr].copy()
    method = f"hybrid_score >= {ANOMALY_PCT} quantile (thr={thr:.4g})"
else:
    anoms = hy.sort_values('Amount', ascending=False).head(TOPK).copy()
    method = "top Amount fallback"

print("Anomaly selection method:", method, "| anomalies found:", len(anoms))

# Plot timeline (Amount vs Date) and highlight anomalies
plt.figure(figsize=(12,4))
plt.plot(hy['Date'], hy['Amount'], marker='.', linestyle='-', alpha=0.45, label='Amount')

# If cluster exists, color anomalies by cluster; else plot red markers
if 'cluster' in anoms.columns and anoms['cluster'].notna().any():
    uniq_clusters = sorted(anoms['cluster'].dropna().unique())
    # pick colors
    import matplotlib.cm as cm
    cmap = cm.get_cmap('tab10', len(uniq_clusters))
    for i, cl in enumerate(uniq_clusters):
        sub = anoms[anoms['cluster']==cl]
        plt.scatter(sub['Date'], sub['Amount'], label=f"Anom cluster {cl}", s=50, color=cmap(i), edgecolors='k', zorder=5)
    # Any anomalies without cluster
    no_cl = anoms[anoms['cluster'].isna()]
    if len(no_cl):
        plt.scatter(no_cl['Date'], no_cl['Amount'], color='red', label='Anom (no cluster)', s=50, edgecolors='k', zorder=5)
else:
    plt.scatter(anoms['Date'], anoms['Amount'], color='red', label='Anomalies', s=50, edgecolors='k', zorder=5)

plt.xlabel("Date")
plt.ylabel("Amount")
plt.title("Transaction timeline with anomalies highlighted")
plt.legend(ncol=2, bbox_to_anchor=(1.02,1), loc='upper left')
plt.tight_layout()
plt.savefig(OUT_PNG, dpi=300, bbox_inches='tight')
plt.show()
print("Saved timeline:", OUT_PNG)

# Export top anomalies CSV (TOPK rows by priority score)
if 'hybrid_score' in hy.columns:
    top = hy.sort_values('hybrid_score', ascending=False).head(TOPK)
elif 'anomaly_score' in hy.columns:
    top = hy.sort_values('anomaly_score', ascending=False).head(TOPK)
elif 'isof_score' in hy.columns:
    top = hy.sort_values('isof_score', ascending=False).head(TOPK)
else:
    top = hy.sort_values('Amount', ascending=False).head(TOPK)

cols_out = ['Date','Amount','Category','YYYYMM']
# Include cluster if exists
if 'cluster' in top.columns:
    cols_out.append('cluster')
# Include any score columns present
for c in ['hybrid_score','isof_score','ocsvm_score','anomaly_score','hybrid_flag','anomaly_abs']:
    if c in top.columns:
        cols_out.append(c)
cols_out = [c for c in cols_out if c in top.columns]
top[cols_out].to_csv(OUT_TOP, index=False)
print("Saved top anomalies CSV:", OUT_TOP)
display(top[cols_out].head(10))

"""### Phase 8: Classification ( Data Mining Technique # 4 )"""

# Install dependencies
!pip install -q xgboost shap joblib

# Robust common preprocessing + fallback pseudo-label creation
import os, warnings
warnings.filterwarnings("ignore")
import numpy as np, pandas as pd, joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Parameters
PCT_LABEL = 0.75        # percentile for pseudo-labeling (top 25% => risky)
TEST_SIZE = 0.25
RANDOM_STATE = 42

# Load window features
if os.path.exists("window_features_with_clusters.csv"):
    wf = pd.read_csv("window_features_with_clusters.csv")
elif os.path.exists("window_features.csv"):
    wf = pd.read_csv("window_features.csv")
else:
    raise FileNotFoundError("window_features.csv or window_features_with_clusters.csv not found. Run Phase4/6.")

print("Loaded window_features shape:", wf.shape)

# Create label_risk if missing
if 'label_risk' in wf.columns:
    print("label_risk already present — using existing labels.")
else:

    # Create from anomaly_scores_comparison.csv when available
    if os.path.exists("anomaly_scores_comparison.csv"):
        an = pd.read_csv("anomaly_scores_comparison.csv", parse_dates=['Date'])
        an['YYYYMM'] = pd.to_datetime(an['Date']).dt.to_period('M').astype(str)
        monthly_an_rate = an.groupby('YYYYMM')['hybrid_flag'].mean().rename('anomaly_rate').reset_index()
        wf = wf.merge(monthly_an_rate, on='YYYYMM', how='left')
        wf['anomaly_rate'] = wf['anomaly_rate'].fillna(0.0)
        th = wf['anomaly_rate'].quantile(PCT_LABEL)
        wf['label_risk'] = (wf['anomaly_rate'] >= th).astype(int)
        print(f"Created label_risk from anomaly_rate >= {PCT_LABEL*100:.0f}th percentile (th={th:.4f})")
    else:

        # FALLBACK: create explainable pseudo-labels using Amount_sum and spend_volatility
        # Ensure required columns exist
        if 'Amount_sum' not in wf.columns:
            candidates = [c for c in wf.columns if 'amount' in c.lower() or 'sum' in c.lower()]
            if candidates:
                amt_col = candidates[0]
                wf = wf.rename(columns={amt_col: 'Amount_sum'})
                print(f"Renamed {amt_col} -> Amount_sum (used for pseudo-labeling).")
            else:
                raise ValueError("No Amount_sum column found in window_features. Required for pseudo-labeling fallback.")
        if 'spend_volatility' not in wf.columns:

            # Compute from Amount_std or similar
            if 'Amount_std' in wf.columns:
                wf = wf.rename(columns={'Amount_std':'spend_volatility'})
                print("Renamed Amount_std -> spend_volatility (used for pseudo-labeling).")
            else:

                # If not available compute from source cleaned_data if present
                print("Warning: spend_volatility not found; creating from Amount_std if available else filling zeros.")
                wf['spend_volatility'] = wf.get('Amount_std', 0.0)

        # Compute thresholds
        th_amt = wf['Amount_sum'].quantile(PCT_LABEL)
        th_vol = wf['spend_volatility'].quantile(PCT_LABEL)
        wf['label_risk'] = ((wf['Amount_sum'] >= th_amt) | (wf['spend_volatility'] >= th_vol)).astype(int)
        print(f"Pseudo-labels created: Amount_sum >= {PCT_LABEL*100:.0f}th pct (th={th_amt:.2f}) OR spend_vol >= {PCT_LABEL*100:.0f}th pct (th={th_vol:.2f})")

# Build feature matrix
drop_cols = set(['YYYYMM','pca1','pca2','label_risk'])
feat_cols = [c for c in wf.columns if c not in drop_cols]
if len(feat_cols) == 0:
    raise ValueError("No feature columns found in window_features after dropping label columns.")

X_df = wf[feat_cols].copy()
y = wf['label_risk'].astype(int).values

# Convert non-numeric and handle NaNs
for c in X_df.columns:
    if not np.issubdtype(X_df[c].dtype, np.number):
        X_df[c] = pd.to_numeric(X_df[c], errors='coerce')

nan_frac = X_df.isna().mean()
drop_cols_nan = nan_frac[nan_frac > 0.5].index.tolist()
if drop_cols_nan:
    print("Dropping columns with >50% NaN:", drop_cols_nan)
    X_df = X_df.drop(columns=drop_cols_nan)

# Fill remaining NaNs with median
X_df = X_df.fillna(X_df.median())

# Final shape checks
X = X_df.values
if X.ndim != 2:
    X = X.reshape(-1, 1)
if np.isnan(X).any():
    raise ValueError("Feature matrix contains NaN after cleaning. Inspect X_df.")

unique, counts = np.unique(y, return_counts=True)
print("Label distribution:", dict(zip(unique, counts)))
if len(unique) < 2:
    # Try relaxing PCT_LABEL for pseudo-label creation (lower threshold) before failing
    if 'label_risk' not in wf.columns:
        alt_pct = 0.66
        print(f"Only one label present. Attempting relaxed pseudo-labeling with percentile={alt_pct:.2f}...")
        th_amt = wf['Amount_sum'].quantile(alt_pct)
        th_vol = wf['spend_volatility'].quantile(alt_pct)
        wf['label_risk'] = ((wf['Amount_sum'] >= th_amt) | (wf['spend_volatility'] >= th_vol)).astype(int)
        y = wf['label_risk'].values
        unique, counts = np.unique(y, return_counts=True)
        print("New label distribution:", dict(zip(unique, counts)))
        if len(unique) < 2:
            raise ValueError("Unable to create two classes automatically. Please provide labels or lower PCT_LABEL manually.")
    else:
        raise ValueError("Only one class present in existing label_risk. Provide more balanced labels.")

# Train/test split & scale
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y)
scaler = StandardScaler().fit(X_train)
X_train_s = scaler.transform(X_train)
X_test_s = scaler.transform(X_test)

# Persist prepared data & feature names
joblib.dump((X_train_s, X_test_s, y_train, y_test), "phase8_data.joblib")
joblib.dump(scaler, "phase8_scaler.joblib")
pd.Series(feat_cols).to_csv("phase8_feat_cols.csv", index=False)

print("Saved phase8_data.joblib, phase8_scaler.joblib, phase8_feat_cols.csv")
print("Train shape:", X_train_s.shape, "Test shape:", X_test_s.shape)
print("Feature columns (first 10):", feat_cols[:10])

"""1. Logistic Regression"""

import os, warnings, joblib, numpy as np, pandas as pd
warnings.filterwarnings("ignore")

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report
from sklearn.preprocessing import MinMaxScaler

# Paths
DATA_FILE = "phase8_data.joblib"
FEAT_FILE = "phase8_feat_cols.csv"
MODEL_OUT = "model_logistic.joblib"
SCALER_OUT = "phase8_scaler.joblib"
SUMMARY_OUT = "logistic_eval_summary.csv"

# Load prepared scaled data
if not os.path.exists(DATA_FILE):
    raise FileNotFoundError("phase8_data.joblib not found. Run common preprocessing cell first.")

X_train_s, X_test_s, y_train, y_test = joblib.load(DATA_FILE)

# Train logistic
lr = LogisticRegression(max_iter=2000, random_state=42)
lr.fit(X_train_s, y_train)
joblib.dump(lr, MODEL_OUT)

# Predictions and probabilities
y_pred = lr.predict(X_test_s)
if hasattr(lr, "predict_proba"):
    y_prob = lr.predict_proba(X_test_s)[:,1]
elif hasattr(lr, "decision_function"):

    # Scale decision_function to 0-1 for ROC
    df_vals = lr.decision_function(X_test_s).reshape(-1,1)
    y_prob = MinMaxScaler().fit_transform(df_vals).ravel()
else:
    y_prob = y_pred

# Metrics
acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred, zero_division=0)
rec = recall_score(y_test, y_pred, zero_division=0)
f1 = f1_score(y_test, y_pred, zero_division=0)
try:
    roc = roc_auc_score(y_test, y_prob) if len(np.unique(y_test))>1 else None
except Exception:
    roc = None

print("=== Logistic Regression ===")
print("Train shape:", X_train_s.shape, "Test shape:", X_test_s.shape)
print("Accuracy:", round(acc,4))
print("Precision:", round(prec,4))
print("Recall:", round(rec,4))
print("F1:", round(f1,4))
print("ROC-AUC:", round(roc,4) if roc is not None else None)
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=0))

# Save summary CSV
summary = pd.DataFrame([{
    'model':'logistic_regression',
    'accuracy':round(acc,4),
    'precision':round(prec,4),
    'recall':round(rec,4),
    'f1':round(f1,4),
    'roc_auc': round(roc,4) if roc is not None else None,
    'n_train': X_train_s.shape[0],
    'n_test': X_test_s.shape[0]
}])
summary.to_csv(SUMMARY_OUT, index=False)
print("\nSaved model:", MODEL_OUT, "summary:", SUMMARY_OUT)

# Load feature names if available
feat_cols = None
if os.path.exists(FEAT_FILE):
    try:
        # try headerless
        tmp = pd.read_csv(FEAT_FILE, header=None)
        feat_cols = tmp.iloc[:,0].astype(str).tolist()
    except Exception:
        try:
            tmp = pd.read_csv(FEAT_FILE)
            feat_cols = tmp.columns.astype(str).tolist()
        except Exception:
            feat_cols = None

# Get coef array
coef_arr = lr.coef_.ravel()
n_coef = coef_arr.size

# Align or create feature names
if feat_cols is None:
    feat_cols = [f"f{i}" for i in range(n_coef)]
elif len(feat_cols) != n_coef:
    if len(feat_cols) > n_coef:
        feat_cols = feat_cols[:n_coef]
    else:
        feat_cols = feat_cols + [f"f{i}" for i in range(len(feat_cols), n_coef)]

# Build and show top features by absolute coefficient
coef_df = pd.DataFrame({'feature': feat_cols, 'abs_coef': np.abs(coef_arr)})
coef_df = coef_df.sort_values('abs_coef', ascending=False).reset_index(drop=True)
print("\nTop features by |coefficient|:")
display(coef_df.head(10))

# Compute simple sign-aware coefficients table
coef_df_full = pd.DataFrame({'feature': feat_cols, 'coef': coef_arr})
coef_df_full = coef_df_full.sort_values('coef', ascending=False).reset_index(drop=True)
print("\nTop positive coefficients (influence towards class=1):")
display(coef_df_full.head(8))
print("\nTop negative coefficients (influence towards class=0):")
display(coef_df_full.tail(8).sort_values('coef'))

"""2. Random Forest"""

import os, joblib, numpy as np, pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report

DATA_FILE = "phase8_data.joblib"
FEAT_FILE = "phase8_feat_cols.csv"
MODEL_OUT = "model_random_forest.joblib"
SUMMARY_OUT = "random_forest_eval_summary.csv"

X_train_s, X_test_s, y_train, y_test = joblib.load(DATA_FILE)

rf = RandomForestClassifier(n_estimators=200, random_state=42)
rf.fit(X_train_s, y_train)
joblib.dump(rf, MODEL_OUT)

# Predict and Probabilities
y_pred = rf.predict(X_test_s)
y_prob = rf.predict_proba(X_test_s)[:,1] if hasattr(rf, "predict_proba") else y_pred

# Metrics
acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred, zero_division=0)
rec = recall_score(y_test, y_pred, zero_division=0)
f1 = f1_score(y_test, y_pred, zero_division=0)
roc = roc_auc_score(y_test, y_prob) if len(np.unique(y_test))>1 else None

print("=== Random Forest ===")
print("Accuracy:", round(acc,4), "Precision:", round(prec,4), "Recall:", round(rec,4), "F1:", round(f1,4), "ROC-AUC:", round(roc,4) if roc is not None else None)
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification report:\n", classification_report(y_test, y_pred, zero_division=0))

pd.DataFrame([{
    'model':'random_forest','accuracy':round(acc,4),'precision':round(prec,4),
    'recall':round(rec,4),'f1':round(f1,4),'roc_auc': round(roc,4) if roc is not None else None,
    'n_train': X_train_s.shape[0],'n_test': X_test_s.shape[0]
}]).to_csv(SUMMARY_OUT, index=False)

# Feature alignment
feat_cols = None
if os.path.exists(FEAT_FILE):
    try:
        tmp = pd.read_csv(FEAT_FILE, header=None)
        feat_cols = tmp.iloc[:,0].astype(str).tolist()
    except:
        try:
            tmp = pd.read_csv(FEAT_FILE)
            feat_cols = list(tmp.columns)
        except:
            feat_cols = None

imp = rf.feature_importances_
n_imp = imp.size

if feat_cols is None:
    feat_cols = [f"f{i}" for i in range(n_imp)]
elif len(feat_cols) != n_imp:
    if len(feat_cols) > n_imp:
        feat_cols = feat_cols[:n_imp]
    else:
        feat_cols = feat_cols + [f"f{i}" for i in range(len(feat_cols), n_imp)]

imp_df = pd.DataFrame({'feature': feat_cols, 'importance': imp})
imp_df = imp_df.sort_values('importance', ascending=False).reset_index(drop=True)
print("\nTop features by importance (Random Forest):")
display(imp_df.head(10))

"""3. XGBoost"""

import os, joblib, warnings
warnings.filterwarnings("ignore")
import numpy as np, pandas as pd

import xgboost as xgb
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report

DATA_FILE = "phase8_data.joblib"
FEAT_FILE = "phase8_feat_cols.csv"
MODEL_OUT = "model_xgboost.joblib"
SUMMARY_OUT = "xgboost_eval_summary.csv"

if not os.path.exists(DATA_FILE):
    raise FileNotFoundError("phase8_data.joblib not found. Run common preprocessing cell first.")

X_train_s, X_test_s, y_train, y_test = joblib.load(DATA_FILE)

xgbc = xgb.XGBClassifier(n_estimators=200, use_label_encoder=False, eval_metric='logloss', random_state=42)
xgbc.fit(X_train_s, y_train)
joblib.dump(xgbc, MODEL_OUT)

y_pred = xgbc.predict(X_test_s)
y_prob = xgbc.predict_proba(X_test_s)[:,1] if hasattr(xgbc, "predict_proba") else y_pred

acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred, zero_division=0)
rec = recall_score(y_test, y_pred, zero_division=0)
f1 = f1_score(y_test, y_pred, zero_division=0)
roc = roc_auc_score(y_test, y_prob) if len(np.unique(y_test))>1 else None

print("=== XGBoost ===")
print("Train shape:", X_train_s.shape, "Test shape:", X_test_s.shape)
print("Accuracy:", round(acc,4))
print("Precision:", round(prec,4))
print("Recall:", round(rec,4))
print("F1:", round(f1,4))
print("ROC-AUC:", round(roc,4) if roc is not None else None)
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, zero_division=0))

pd.DataFrame([{
    'model':'xgboost','accuracy':round(acc,4),'precision':round(prec,4),
    'recall':round(rec,4),'f1':round(f1,4),'roc_auc': round(roc,4) if roc is not None else None,
    'n_train': X_train_s.shape[0],'n_test': X_test_s.shape[0]
}]).to_csv(SUMMARY_OUT, index=False)
print("Saved model:", MODEL_OUT, "summary:", SUMMARY_OUT)

# Feature alignment
feat_cols = None
if os.path.exists(FEAT_FILE):
    try:
        tmp = pd.read_csv(FEAT_FILE, header=None)
        feat_cols = tmp.iloc[:,0].astype(str).tolist()
    except:
        try:
            tmp = pd.read_csv(FEAT_FILE)
            feat_cols = list(tmp.columns)
        except:
            feat_cols = None

# Get importance from booster (gain)
try:
    booster = xgbc.get_booster()
    imp_dict = booster.get_score(importance_type='gain')

    # Convert to DataFrame
    imp_df = pd.DataFrame(list(imp_dict.items()), columns=['f','gain'])

    # Map f names to feat_cols if available
    if feat_cols is not None:
        imp_df['feature'] = imp_df['f'].apply(lambda s: feat_cols[int(s[1:])] if str(s).startswith('f') and int(s[1:]) < len(feat_cols) else s)
    else:
        imp_df['feature'] = imp_df['f']
    imp_df = imp_df[['feature','gain']].sort_values('gain', ascending=False).reset_index(drop=True)
    print("\nTop features by gain (XGBoost):")
    display(imp_df.head(10))
except Exception as e:
    print("XGBoost importance extraction failed:", str(e))

"""*Comparative study*"""

import os, joblib, pandas as pd, numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.preprocessing import MinMaxScaler

DATA_FILE = "phase8_data.joblib"

# Load clean test data
if not os.path.exists(DATA_FILE):
    raise FileNotFoundError("Run the common preprocessing cell first (phase8_data.joblib missing).")

X_train_s, X_test_s, y_train, y_test = joblib.load(DATA_FILE)

# Helper function to evaluate models
def evaluate_model(model, X_test, y_test, name):
    y_pred = model.predict(X_test)

    if hasattr(model, "predict_proba"):
        y_prob = model.predict_proba(X_test)[:,1]
    elif hasattr(model, "decision_function"):
        df_vals = model.decision_function(X_test).reshape(-1,1)
        y_prob = MinMaxScaler().fit_transform(df_vals).ravel()
    else:
        y_prob = y_pred

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, zero_division=0)
    rec = recall_score(y_test, y_pred, zero_division=0)
    f1 = f1_score(y_test, y_pred, zero_division=0)
    roc = roc_auc_score(y_test, y_prob) if len(np.unique(y_test)) > 1 else None

    return {
        "Model": name,
        "Accuracy": round(acc, 4),
        "Precision": round(prec, 4),
        "Recall": round(rec, 4),
        "F1_Score": round(f1, 4),
        "ROC_AUC": round(roc, 4) if roc is not None else None
    }

# Load models
models = {}

if os.path.exists("model_logistic.joblib"):
    models["Logistic Regression"] = joblib.load("model_logistic.joblib")
else:
    print("Warning: Logistic Regression model not found.")

if os.path.exists("model_random_forest.joblib"):
    models["Random Forest"] = joblib.load("model_random_forest.joblib")
else:
    print("Warning: Random Forest model not found.")

if os.path.exists("model_xgboost.joblib"):
    models["XGBoost"] = joblib.load("model_xgboost.joblib")
else:
    print("Warning: XGBoost model not found.")

# Evaluate & compare
results = []
for name, model in models.items():
    scores = evaluate_model(model, X_test_s, y_test, name)
    results.append(scores)

# Convert to DataFrame
compare_df = pd.DataFrame(results)
compare_df = compare_df.set_index("Model")

print("===== Comparative Study: Model Performance =====")
display(compare_df)

# Save summary
compare_df.to_csv("compare_classification_models_summary.csv")
print("Saved: compare_classification_models_summary.csv")

# ROC + PR curves for Logistic, Random Forest, XGBoost
import os, joblib, numpy as np, pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc, precision_recall_curve, average_precision_score

# Files
DATA_FILE = "phase8_data.joblib"
OUT_PNG = "roc_pr_compare.png"
OUT_CSV = "roc_pr_data.csv"

if not os.path.exists(DATA_FILE):
    raise FileNotFoundError("phase8_data.joblib missing. Run preprocessing cell first.")
X_train_s, X_test_s, y_train, y_test = joblib.load(DATA_FILE)

models = {}
if os.path.exists("model_logistic.joblib"):
    models["Logistic Regression"] = joblib.load("model_logistic.joblib")
if os.path.exists("model_random_forest.joblib"):
    models["Random Forest"] = joblib.load("model_random_forest.joblib")
if os.path.exists("model_xgboost.joblib"):
    models["XGBoost"] = joblib.load("model_xgboost.joblib")
if not models:
    raise FileNotFoundError("No models found. Train models first.")

plt.figure(figsize=(12,5))

# ROC subplot
plt.subplot(1,2,1)
roc_rows = []
for name, m in models.items():
    if hasattr(m, "predict_proba"):
        prob = m.predict_proba(X_test_s)[:,1]
    elif hasattr(m, "decision_function"):
        prob = m.decision_function(X_test_s)
    else:
        prob = m.predict(X_test_s)
    fpr, tpr, _ = roc_curve(y_test, prob)
    rauc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{name} (AUC={rauc:.3f})")
    roc_rows.append({"model":name, "fpr":fpr.tolist(), "tpr":tpr.tolist(), "auc":rauc})
plt.plot([0,1],[0,1], 'k--', alpha=0.4)
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()

# PR subplot
plt.subplot(1,2,2)
pr_rows = []
for name, m in models.items():
    if hasattr(m, "predict_proba"):
        prob = m.predict_proba(X_test_s)[:,1]
    elif hasattr(m, "decision_function"):
        prob = m.decision_function(X_test_s)
    else:
        prob = m.predict(X_test_s)
    prec, rec, _ = precision_recall_curve(y_test, prob)
    ap = average_precision_score(y_test, prob)
    plt.plot(rec, prec, label=f"{name} (AP={ap:.3f})")
    pr_rows.append({"model":name, "recall":rec.tolist(), "precision":prec.tolist(), "ap":ap})
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve")
plt.legend()
plt.tight_layout()
plt.savefig(OUT_PNG, dpi=300, bbox_inches='tight')
plt.show()

# Save CSV
df_out = pd.DataFrame(roc_rows)
df_pr = pd.DataFrame(pr_rows)
df_merge = df_out.merge(df_pr, on="model", how="outer")
df_merge.to_csv(OUT_CSV, index=False)
print("Saved:", OUT_PNG, OUT_CSV)

"""## Final Summary

This final section aggregates the key outputs of the entire data mining pipeline — including clustering, anomaly detection, frequent pattern mining, and classification modeling — into a single consolidated summary.
Because training and testing feature matrices may have slightly different feature sets due to category encoding, I applied feature alignment.
This ensures both matrices have identical columns (trim/pad) before training models.
This prevents shape mismatches and guarantees fair model comparison.

The cell below:

- Loads the saved metrics from all models (Logistic Regression, Random Forest, XGBoost)

- Computes or retrieves accuracy, precision, recall, F1-score and ROC-AUC

- Summarizes cluster behavior (number of clusters, average anomaly rate)

- Summarizes anomaly detection outputs (flag counts, timeline span)

- Counts frequent itemsets and association rules

- Includes early-warning detection statistics (if generated)

- Saves all results into final_summary_report.csv and final_summary_report.json

- Displays the complete table for quick review

- Lists all key project files generated during execution

This marks the completion of the project and provides a comprehensive, evaluable output for report writing, presentation preparation, and external verification.
"""

import os, json, joblib, pandas as pd, numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.preprocessing import MinMaxScaler

OUT_CSV = "final_summary_report.csv"
OUT_JSON = "final_summary_report.json"

def load_summary_csv(name):
    f = f"{name}_eval_summary.csv"
    if os.path.exists(f):
        try:
            return pd.read_csv(f)
        except:
            return None
    return None

def compute_metrics_from_model(model_path, X_test, y_test):
    try:
        m = joblib.load(model_path)
        y_pred = m.predict(X_test)
        if hasattr(m, "predict_proba"):
            y_prob = m.predict_proba(X_test)[:,1]
        elif hasattr(m, "decision_function"):
            dfv = m.decision_function(X_test).reshape(-1,1)
            y_prob = MinMaxScaler().fit_transform(dfv).ravel()
        else:
            y_prob = y_pred
        return {
            'accuracy': round(accuracy_score(y_test, y_pred),4),
            'precision': round(precision_score(y_test, y_pred, zero_division=0),4),
            'recall': round(recall_score(y_test, y_pred, zero_division=0),4),
            'f1': round(f1_score(y_test, y_pred, zero_division=0),4),
            'roc_auc': round(roc_auc_score(y_test, y_prob),4) if len(np.unique(y_test))>1 else None
        }
    except Exception:
        return None

# Collect model metrics
models = {
    "Logistic Regression": "model_logistic.joblib",
    "Random Forest": "model_random_forest.joblib",
    "XGBoost": "model_xgboost.joblib"
}

model_rows = []

X_test_s = y_test = None
if os.path.exists("phase8_data.joblib"):
    try:
        X_train_s, X_test_s, y_train, y_test = joblib.load("phase8_data.joblib")
    except:
        X_test_s = y_test = None

for mname, mpath in models.items():
    row = {"model": mname}

    csv_df = load_summary_csv(mname.split()[0].lower() if mname.startswith("Logistic") else mname.lower().replace(" ","_"))
    if csv_df is not None and not csv_df.empty:


        r = csv_df.iloc[0].to_dict()
        row.update({
            'accuracy': r.get('accuracy'),
            'precision': r.get('precision'),
            'recall': r.get('recall'),
            'f1': r.get('f1'),
            'roc_auc': r.get('roc_auc')
        })
    elif os.path.exists(mpath) and X_test_s is not None and y_test is not None:
        mres = compute_metrics_from_model(mpath, X_test_s, y_test)
        if mres:
            row.update(mres)
        else:
            row.update({'accuracy':None,'precision':None,'recall':None,'f1':None,'roc_auc':None})
    else:
        row.update({'accuracy':None,'precision':None,'recall':None,'f1':None,'roc_auc':None})
    model_rows.append(row)

model_df = pd.DataFrame(model_rows).set_index('model')

# Cluster summary (counts, mean anomaly rate)
cluster_summary_file = "cluster_summary.csv"
cluster_stats = {}
if os.path.exists(cluster_summary_file):
    try:
        cs = pd.read_csv(cluster_summary_file)
        cluster_stats['n_clusters'] = cs.shape[0]

        # Attempt to get anomaly rate column
        ar_cols = [c for c in cs.columns if 'anomaly' in c.lower() or 'ratio' in c.lower()]
        cluster_stats['mean_anomaly_rate'] = float(cs[ar_cols[0]].mean()) if ar_cols else None
    except Exception:
        cluster_stats['n_clusters'] = None
        cluster_stats['mean_anomaly_rate'] = None
else:
    cluster_stats['n_clusters'] = None
    cluster_stats['mean_anomaly_rate'] = None

# Anomaly summary counts
anomaly_file = "hybrid_anomaly_results.csv"
an_stats = {}
if os.path.exists(anomaly_file):
    try:
        hy = pd.read_csv(anomaly_file, parse_dates=['Date'], infer_datetime_format=True)
        an_stats['n_anomaly_rows'] = int(hy.shape[0])

        if 'hybrid_flag' in hy.columns:
            an_stats['n_flagged'] = int(hy['hybrid_flag'].sum())
        else:
            an_stats['n_flagged'] = None
        an_stats['anomaly_time_range_start'] = str(hy['Date'].min()) if 'Date' in hy.columns else None
        an_stats['anomaly_time_range_end'] = str(hy['Date'].max()) if 'Date' in hy.columns else None
    except Exception:
        an_stats['n_anomaly_rows'] = None
        an_stats['n_flagged'] = None
else:
    an_stats['n_anomaly_rows'] = None
    an_stats['n_flagged'] = None
    an_stats['anomaly_time_range_start'] = None
    an_stats['anomaly_time_range_end'] = None

# Frequent itemsets / rules counts
fi_count = None
if os.path.exists("ap_top_itemsets.csv"):
    try:
        fi_count = int(pd.read_csv("ap_top_itemsets.csv").shape[0])
    except:
        fi_count = None

rules_count = None
if os.path.exists("ap_top_rules.csv"):
    try:
        rules_count = int(pd.read_csv("ap_top_rules.csv").shape[0])
    except:
        rules_count = None

# Early-warning summary if exists
early_file = "early_warning_summary.csv"
early_stats = {}
if os.path.exists(early_file):
    try:
        ef = pd.read_csv(early_file)
        early_stats['lead_time_points'] = ef.shape[0]


        if 'detection_rate' in ef.columns:
            early_stats['detection_rate_1'] = float(ef['detection_rate'].iloc[0])
        else:
            early_stats['detection_rate_1'] = None
    except:
        early_stats['lead_time_points'] = None
        early_stats['detection_rate_1'] = None
else:
    early_stats['lead_time_points'] = None
    early_stats['detection_rate_1'] = None

# Prepare final summary dataframe
meta = {
    'n_clusters': cluster_stats['n_clusters'],
    'mean_cluster_anomaly_rate': cluster_stats['mean_anomaly_rate'],
    'n_anomaly_rows': an_stats['n_anomaly_rows'],
    'n_anomaly_flagged': an_stats['n_flagged'],
    'anomaly_time_start': an_stats.get('anomaly_time_range_start'),
    'anomaly_time_end': an_stats.get('anomaly_time_range_end'),
    'n_frequent_itemsets': fi_count,
    'n_association_rules': rules_count,
    'early_warning_points': early_stats['lead_time_points'],
    'early_warning_detection_sample': early_stats['detection_rate_1']
}

# Save model metrics table and meta as final_report
try:
    model_df.to_csv("model_metrics_summary.csv")
except:
    pass

final_meta = meta.copy()

# Include model summary in the JSON output as dict
final_meta['models'] = model_df.reset_index().to_dict(orient='records')

# Write outputs
pd.DataFrame([final_meta]).to_csv(OUT_CSV, index=False)
with open(OUT_JSON, "w") as f:
    json.dump(final_meta, f, indent=2)

# Print
print("=== FINAL SUMMARY ===\n")
print("Model metrics:")
display(model_df)
print("\nMeta summary:")
for k,v in final_meta.items():
    if k != 'models':
        print(f"{k}: {v}")
print("\nSaved:", OUT_CSV, OUT_JSON, "and model_metrics_summary.csv (if created)")

# Print short list of key files present
print("\nKey files in working directory (filtered):")
key_prefixes = ['model_','phase8_','window_features','hybrid','cluster_summary','ap_','roc','pr','anomaly','final_summary','top_anomalies']
files = sorted([f for f in os.listdir('.') if any(f.startswith(p) or p in f for p in key_prefixes)])
for f in files:
    print("-", f)

files = [
 "cleaned_data.csv",
 "basket_matrix_monthly.csv",
 "window_features.csv",
 "window_features_with_clusters.csv",
 "clustered_window_features_kmeans.csv",
 "clustered_window_features_dbscan.csv",
 "isof_results.csv",
 "ocsvm_results.csv",
 "hybrid_anomaly_results.csv",
 "top_anomalies.csv",
 "phase8_feat_cols.csv",
 "compare_kmeans_dbscan_summary.csv",
 "compare_classification_models_summary.csv"
]

for f in files:
  if os.path.exists(f):
    print(f"\n=== {f} (head) ===")
    try:
      print(pd.read_csv(f).head(5).to_string(index=False))
    except Exception as e:
      print("Error reading:", e)
  else:
    print(f"\n*** {f} NOT FOUND in working dir.")